
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABS AND ANDBIT ARRAY CADENA CARACTER CHAR CORDER CORIZQ DECIMAL DIFERENTE DIVISION DOSPUNTOS ENTERO EXIT FLOAT GOTO ID IF IGUAL IGUALIGUAL INTEGER LLAVEDER LLAVEIZQ MAIN MAS MAYOR MAYORIGUAL MENOR MENORIGUAL MENOS MODULAR MULTIPLICACION NOT NOTBIT OR ORBIT PARDER PARIZQ PRINT PYCOMA READ SHIFTDER SHIFTIZQ UNSET VARIABLE XOR XORBITinit : instrucciones instrucciones : instrucciones instruccion  instrucciones : instruccion  instruccion : pmain\n                    | petiquetapmain : MAIN DOSPUNTOS sentencias sentencias    :   sentencias sentenciasentencias    :   sentenciasentencia : pvariable\n    pvariable : VARIABLE IGUAL operacion PYCOMA operacion   :   valor MAS valor\n                    |   valor MENOS valor\n                    |   valor MULTIPLICACION valor\n                    |   valor DIVISION valor\n                    |   valor MODULAR valor\n     operacion     :   valor valor    :   ENTERO\n                |   DECIMAL\n    valor    :   CADENA\n                |   CARACTER\n    valor    :   VARIABLE\n    petiqueta : ID DOSPUNTOS sentencias'
    
_lr_action_items = {'MAIN':([0,2,3,4,5,8,11,12,13,15,16,25,],[6,6,-3,-4,-5,-2,-6,-8,-9,-22,-7,-10,]),'ID':([0,2,3,4,5,8,11,12,13,15,16,25,],[7,7,-3,-4,-5,-2,-6,-8,-9,-22,-7,-10,]),'$end':([1,2,3,4,5,8,11,12,13,15,16,25,],[0,-1,-3,-4,-5,-2,-6,-8,-9,-22,-7,-10,]),'DOSPUNTOS':([6,7,],[9,10,]),'VARIABLE':([9,10,11,12,13,15,16,17,25,26,27,28,29,30,],[14,14,14,-8,-9,14,-7,18,-10,18,18,18,18,18,]),'IGUAL':([14,],[17,]),'ENTERO':([17,26,27,28,29,30,],[21,21,21,21,21,21,]),'DECIMAL':([17,26,27,28,29,30,],[22,22,22,22,22,22,]),'CADENA':([17,26,27,28,29,30,],[23,23,23,23,23,23,]),'CARACTER':([17,26,27,28,29,30,],[24,24,24,24,24,24,]),'MAS':([18,20,21,22,23,24,],[-21,26,-17,-18,-19,-20,]),'MENOS':([18,20,21,22,23,24,],[-21,27,-17,-18,-19,-20,]),'MULTIPLICACION':([18,20,21,22,23,24,],[-21,28,-17,-18,-19,-20,]),'DIVISION':([18,20,21,22,23,24,],[-21,29,-17,-18,-19,-20,]),'MODULAR':([18,20,21,22,23,24,],[-21,30,-17,-18,-19,-20,]),'PYCOMA':([18,19,20,21,22,23,24,31,32,33,34,35,],[-21,25,-16,-17,-18,-19,-20,-11,-12,-13,-14,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,8,]),'pmain':([0,2,],[4,4,]),'petiqueta':([0,2,],[5,5,]),'sentencias':([9,10,],[11,15,]),'sentencia':([9,10,11,15,],[12,12,16,16,]),'pvariable':([9,10,11,15,],[13,13,13,13,]),'operacion':([17,],[19,]),'valor':([17,26,27,28,29,30,],[20,31,32,33,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','Gramatica.py',210),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','Gramatica.py',215),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones2','Gramatica.py',223),
  ('instruccion -> pmain','instruccion',1,'p_instruccion','Gramatica.py',229),
  ('instruccion -> petiqueta','instruccion',1,'p_instruccion','Gramatica.py',230),
  ('pmain -> MAIN DOSPUNTOS sentencias','pmain',3,'p_pmain','Gramatica.py',234),
  ('sentencias -> sentencias sentencia','sentencias',2,'p_sentencias','Gramatica.py',246),
  ('sentencias -> sentencia','sentencias',1,'p_sentencias2','Gramatica.py',253),
  ('sentencia -> pvariable','sentencia',1,'p_sentencia','Gramatica.py',260),
  ('pvariable -> VARIABLE IGUAL operacion PYCOMA','pvariable',4,'p_pvariable','Gramatica.py',265),
  ('operacion -> valor MAS valor','operacion',3,'p_operaciones','Gramatica.py',276),
  ('operacion -> valor MENOS valor','operacion',3,'p_operaciones','Gramatica.py',277),
  ('operacion -> valor MULTIPLICACION valor','operacion',3,'p_operaciones','Gramatica.py',278),
  ('operacion -> valor DIVISION valor','operacion',3,'p_operaciones','Gramatica.py',279),
  ('operacion -> valor MODULAR valor','operacion',3,'p_operaciones','Gramatica.py',280),
  ('operacion -> valor','operacion',1,'p_operacion','Gramatica.py',294),
  ('valor -> ENTERO','valor',1,'p_valor','Gramatica.py',303),
  ('valor -> DECIMAL','valor',1,'p_valor','Gramatica.py',304),
  ('valor -> CADENA','valor',1,'p_valor2','Gramatica.py',309),
  ('valor -> CARACTER','valor',1,'p_valor2','Gramatica.py',310),
  ('valor -> VARIABLE','valor',1,'p_valor3','Gramatica.py',315),
  ('petiqueta -> ID DOSPUNTOS sentencias','petiqueta',3,'p_petiqueta','Gramatica.py',320),
]
